development:
  adapter: postgresql
  encoding: unicode
  database: lylegoff
  username: postgres
  password: carlyle23
  pool: 5
  timeout: 5000


production:
  host: ec2-54-225-116-36.compute-1.amazonaws.com
  adapter: postgresql
  encoding: unicode
  database: d9d8jcjf7i9t15
  username: ovzdgyrevrembf
  password: 4ab317c58212779464e480467eda61f5f5b96c7275f064d448db6adf8963f670
  pool: 5
  timeout: 5000
