Deal.create!([
  {name: "Fire TV Stick 4K with Alexa Voice Remote, streaming media player ", description: "4K streaming media stick with a Wi-Fi antenna ", list_price: nil, sale_price: "49.99", purchase_url: "https://amzn.to/2ZIaSXl", image_url: "<a href=\"https://www.amazon.com/gp/product/B079QHML21/ref=as_li_ss_il?ie=UTF8&linkCode=li2&tag=lylegoffkitst-20&linkId=74c2d17a2addfcb180366f7dbc6599d7\" target=\"_blank\"><img border=\"0\" src=\"//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B079QHML21&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=lylegoffkitst-20\" ></a><img src=\"https://ir-na.amazon-adsystem.com/e/ir?t=lylegoffkitst-20&l=li2&o=1&a=B079QHML21\" width=\"1\" height=\"1\" border=\"0\" alt=\"\" style=\"border:none !important; margin:0px !important;\" />"},
  {name: "Samsung 128GB 100MB/s (U3) MicroSD EVO Select Memory Card with Adapter (MB-ME128GA/AM) ", description: " Up to 100MB/s & 90MB/s read & write speeds respectively; Class 10 UHS 3; Durability: 10,000 mating cycles\r\nHigh-performance for 4K UHD video recording, high resolution pictures, mobile gaming and music, for use in Smartphones, Drones, Android Tablets, Tablet PCs, Action Cameras, DSLRs and more\r\nIncludes: Full-Size adapter for use in Cameras and Laptop/Desktop Computers\r\n10-year limited warranty. For products incompatible with UHS-I interface, the speeds may vary subject to different interface conditions, Read : up to 80MB/s with UHS-1 interface Write : up to 20MB/s with UHS-1 interface\r\n Up to 100MB/s & 90MB/s read & write speeds respectively; Class 10 UHS 3; Durability: 10,000 mating cycles\r\nHigh-performance for 4K UHD video recording, high resolution pictures, mobile gaming and music, for use in Smartphones, Drones, Android Tablets, Tablet PCs, Action Cameras, DSLRs and more\r\nIncludes: Full-Size adapter for use in Cameras and Laptop/Desktop Computers\r\n10-year limited warranty. For products incompatible with UHS-I interface, the speeds may vary subject to different interface conditions, Read : up to 80MB/s with UHS-1 interface Write : up to 20MB/s with UHS-1 interface ", list_price: "24.99", sale_price: "20.99", purchase_url: "https://amzn.to/2VwtJoZ", image_url: "<a href=\"https://www.amazon.com/gp/product/B06XWZWYVP/ref=as_li_ss_il?ie=UTF8&linkCode=li2&tag=lylegoffkitst-20&linkId=ac985ab85e2123cbd6bd80a316b2a367\" target=\"_blank\"><img border=\"0\" src=\"//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B06XWZWYVP&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=lylegoffkitst-20\" ></a><img src=\"https://ir-na.amazon-adsystem.com/e/ir?t=lylegoffkitst-20&l=li2&o=1&a=B06XWZWYVP\" width=\"1\" height=\"1\" border=\"0\" alt=\"\" style=\"border:none !important; margin:0px !important;\" />"},
  {name: "Apple AirPods with Charging Case", description: "\r\n    Amazingly easy to use, AirPods combine intelligent design with breakthrough technology and crystal clear sound.\r\n    Get up to 5 hours of listening time on one charge.\r\n    Or up to 3 hours with just a 15-minute charge in the charging case.\r\n", list_price: "159.0", sale_price: "147.0", purchase_url: "https://amzn.to/2ZGNd9L", image_url: "<a href=\"https://www.amazon.com/gp/product/B01MQWUXZS/ref=as_li_ss_il?ie=UTF8&linkCode=li2&tag=lylegoffkitst-20&linkId=89ce5675dae7202bd703ac99c41fa770\" target=\"_blank\"><img border=\"0\" src=\"//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B01MQWUXZS&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=lylegoffkitst-20\" ></a><img src=\"https://ir-na.amazon-adsystem.com/e/ir?t=lylegoffkitst-20&l=li2&o=1&a=B01MQWUXZS\" width=\"1\" height=\"1\" border=\"0\" alt=\"\" style=\"border:none !important; margin:0px !important;\" />"},
  {name: "Echo Dot (3rd Gen) - Smart speaker with Alexa", description: "\r\n    Our most popular smart speaker - Now with a fabric design and improved speaker for richer and louder sound.\r\n    Voice control your music - Stream songs from Amazon Music, Apple Music, Spotify, Sirius XM, and others. You can also listen to audiobooks from Audible.\r\n    Bigger, better sound - Pair with a second Echo Dot (3rd gen) for rich, stereo sound. Fill your home with music with compatible Echo devices in different rooms.\r\n    Ready to help - Ask Alexa to play music, answer questions, read the news, check the weather, set alarms, control compatible smart home devices, and more.\r\n    Connect with others - Call almost anyone hands-free. Instantly drop in on other rooms in your home or make an announcement to every room with a compatible Echo device.\r\n    Use another speaker - Connect to your own speakers over Bluetooth or with a 3.5 mm audio cable.\r\n    Alexa has skills - With 50,000+ skills, Alexa is always getting smarter and adding new skills like tracking fitness, playing games, and more.\r\n    Voice control your smart home - Turn on lights, adjust thermostats, lock doors, and more with compatible connected devices\r\n", list_price: nil, sale_price: "49.99", purchase_url: "https://amzn.to/2DOB49F", image_url: "<a href=\"https://www.amazon.com/gp/product/B0792K2BK6/ref=as_li_ss_il?ie=UTF8&linkCode=li2&tag=lylegoffkitst-20&linkId=a2e0c5aab82c31ae3965c1b9094e1a40\" target=\"_blank\"><img border=\"0\" src=\"//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B0792K2BK6&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=lylegoffkitst-20\" ></a><img src=\"https://ir-na.amazon-adsystem.com/e/ir?t=lylegoffkitst-20&l=li2&o=1&a=B0792K2BK6\" width=\"1\" height=\"1\" border=\"0\" alt=\"\" style=\"border:none !important; margin:0px !important;\" />"},
  {name: "Samsung 860 EVO 500GB 2.5 Inch SATA III Internal SSD (MZ-76E500B/AM) ", description: " Powered by Samsung V-NAND Technology. Optimized Performance for Everyday Computing\r\nEnhanced Performance: Sequential Read/Write speeds up to 550MB/s and 520MB/s respectively\r\nIdeal for mainstream PCs and laptops for personal, gaming and business use\r\nHardware/Software Compatibility: Windows 8/Windows 7/Windows Server 2003 (32-bit and 64-bit), Vista (SP1 and above), XP (SP2 and above), MAC OSX, and Linux\r\nIncluded Contents: 2.5\" (7mm) SATA III (6Gb/s) SSD & User Manual (All Other Cables, Screws, Brackets Not Included). 5-Year Warranty ", list_price: "109.99", sale_price: "79.99", purchase_url: "https://amzn.to/2XVGkQ3", image_url: "<a href=\"https://www.amazon.com/gp/product/B0781Z7Y3S/ref=as_li_ss_il?ie=UTF8&linkCode=li2&tag=lylegoffkitst-20&linkId=6dd20191b11eb1b29e6670d926cf35d9\" target=\"_blank\"><img border=\"0\" src=\"//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B0781Z7Y3S&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=lylegoffkitst-20\" ></a><img src=\"https://ir-na.amazon-adsystem.com/e/ir?t=lylegoffkitst-20&l=li2&o=1&a=B0781Z7Y3S\" width=\"1\" height=\"1\" border=\"0\" alt=\"\" style=\"border:none !important; margin:0px !important;\" />"}
])
Article.create!([
  {title: "New article link", text: "<%= link_to 'New Article', new_article_path %>"},
  {title: "Add class to submit button", text: "<%= f.submit class: 'btn btn-default' %>"},
  {title: "Check repository into master", text: "git push origin master -f"},
  {title: "List all articles", text: "<% @articles.each do |article| %>\r\n    <tr>\r\n      <td><%= article.id %></td>\r\n      <td><%= article.title %></td>\r\n      <td><%= article.text %></td>\r\n      <td><%= link_to 'Show', article_path(article) %></td>\r\n      <td><%= link_to 'Edit', edit_article_path(article) %></td>\r\n      <td><%= link_to 'Destroy', article_path(article),\r\n              method: :delete,\r\n              data: { confirm: 'Are you sure?' } %></td>\r\n    </tr>\r\n  <% end %>"},
  {title: "Link image to root of application", text: "<%= link_to root_path do %>\r\n   <%= image_tag \"image.jpg\", class: \"some css class here\" %>\r\n<% end %>"}
])
Comment.create!([
  {commenter: "Lyle", body: "-f is used to force commit", article_id: 3},
  {commenter: "Lyle", body: "Must do git add . and git commit -m \"Message\" before pushing to master", article_id: 3}
])
Download.create!([
  {name: "Pop!_OS", link: "https://system76.com/pop"},
  {name: "Ubuntu", link: "https://www.ubuntu.com"},
  {name: "Manjaro", link: "https://manjaro.org"},
  {name: "Windows 10 Pro", link: "https://www.newegg.com/Product/Product.aspx?Item=N82E16832588491&cm_sp=Homepage_BS-_-P5_32-588-491-_-04302019"}
])
ImagePost.create!([
  {caption: "Manjaro desktop", link: "https://wallpapercave.com/wp/wp1947761.png"},
  {caption: "Manjaro wallpaper", link: "https://wallpapercave.com/wp/wp1947849.png"},
  {caption: "Manjaro Mountain", link: "https://wallpaperbro.com/img/493222.jpg"},
  {caption: "Grey Manjaro Desktop", link: "http://starbeamrainbowlabs.com/blog/images/20170809-Manjaro-Wallpaper.jpeg"},
  {caption: "Arch linux blue wallpaper", link: "http://www.linuxcmd.org/lcshow/big/54/546983_manjaro-linux-wallpaper.png"},
  {caption: "Green Manjaro wallpaper", link: "https://cn.opendesktop.org/img/3/9/c/f/e06cd827d33007142f9696d3db82e8e8a34c.png"},
  {caption: "Google", link: "https://i.dailymail.co.uk/i/pix/2015/09/01/18/2BE1E88B00000578-3218613-image-m-5_1441127035222.jpg"},
  {caption: "Cool liquid cooled computer", link: "https://ae01.alicdn.com/kf/HTB1j50QKXXXXXbvXFXXq6xXFXXXz/QDIY-PC-D779XL-E-ATX-Large-Motherboard-Personalized-Cool-PC-Case-Water-Cooling-Computer-Case.jpg"},
  {caption: "Vodka Cooling", link: "https://i.ytimg.com/vi/IYTJfLyo_vE/maxresdefault.jpg"},
  {caption: "Liquid cooled computer", link: "https://i.pinimg.com/originals/34/08/8c/34088caf7c5cef08ee69792b3344cacd.jpg"}
])
